//! What an empty demo library starts with.
//!
//! Only the demo has this: `harken-web` is built with no features and never
//! compiles the file, so none of these strings reach the client that talks to
//! a real server. The library there is whatever the scanner found.
//!
//! Everything goes in through `mutate`, not through SQL — the demo runs the
//! same `apply` as every other peer, and seeding it any other way would be
//! showing something the engine did not do.
//!
//! Public-domain recordings on Wikimedia Commons, by way of the mp3 transcode
//! Commons generates for every audio file: a browser plays mp3 everywhere, and
//! Vorbis in an `.ogg` does not play in Safari at all. The URL goes in `file`,
//! which is what that column has always been for, so nothing about the log
//! changes to carry a recording.
//!
//! Every entry was checked, because a dead link here is a silent demo: a
//! licence by Commons' own field, and a transcode that answers `audio/mpeg`
//! to a range request. Almost all of it reserves no rights at all. The
//! exception is [`BRANDENBURG`], which is CC BY and CC BY-SA, so those rows
//! carry a `licence` and the credit is drawn beside the performer — a
//! condition met, rather than a licence quietly ignored.

use crate::{Peer, Source};
use harken::{self as mutators};

/// One row of the tables below.
///
/// A struct rather than a tuple because there are ten of them now and a
/// `("Allegro", "Handel", "Water Music", "Suite No. 2 in D major, HWV 349",
/// 12, "HWV 349", "United States Marine Band", 132, 228661, "https://…")` is
/// a puzzle at every row.
pub struct Seed {
    pub title: &'static str,
    /// Who wrote it. Reaches `media.creator`, which is the kind-neutral line.
    pub composer: &'static str,
    pub album: &'static str,
    /// The suite or book inside the album; empty when the work has none.
    pub part: &'static str,
    /// Position within the album; 0 when nobody said.
    pub track: i64,
    /// `BWV 988`, `HWV 349`; empty for music nobody catalogued.
    pub catalogue: &'static str,
    /// Who played it, which is not who wrote it.
    pub performer: &'static str,
    /// Commons' own licence field, for a recording whose licence asks for a
    /// credit; empty when it asks for nothing. Not a column on `song`: it is
    /// a fact about this demo's sources rather than about music, and the one
    /// place it has to appear is beside the performer it belongs to.
    pub licence: &'static str,
    /// From the tempo marking in the title where there is one; 0 otherwise.
    pub bpm: i64,
    pub ms: i64,
    pub file: &'static str,
}

/// Bach, as far as Commons has him.
///
/// Harvested rather than chosen: every audio file under Commons' own
/// "Compositions by Johann Sebastian Bach", kept when its licence reserves no
/// rights and its transcode answers a range request. That is not the complete
/// works and does not pretend to be — it is what has been recorded, released
/// freely, and put there.
///
/// Everything here reserves no rights at all, which is what the harvest was
/// filtered on. The credited recordings are next door in [`BRANDENBURG`],
/// because they came with a condition and this list did not.
///
/// **One recording per work.** The harvest found two complete Goldbergs —
/// Kimiko Ishizaka's and Shelley Katz's — and both surviving meant sixty-four
/// rows for thirty-two pieces, an album that says 64 tracks, and a scroll
/// through the same variations twice under different titles. A library is
/// what you have, and having a piece twice is not having two pieces. The
/// Ishizaka take stays because her Well-Tempered Clavier is already here, so
/// the Bach keyboard music is one performer rather than two.
///
/// The Brandenburgs are the exception that shows the rule is about *pieces*,
/// not performers: no movement there appears twice, and Nos. 1 and 4 are two
/// recordings between them because that is the only way either is complete.
// BACH-START
pub const BACH: &[Seed] = &[
    Seed {
        title: "Aria",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 1,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 300000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e6/Kimiko_Ishizaka_-_01_-_Aria.ogg/Kimiko_Ishizaka_-_01_-_Aria.ogg.mp3",
    },
    Seed {
        title: "Variatio 1 a 1 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 2,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 115000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/20/Kimiko_Ishizaka_-_02_-_Variatio_1_a_1_Clav.ogg/Kimiko_Ishizaka_-_02_-_Variatio_1_a_1_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 2 a 1 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 3,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 124000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9e/Kimiko_Ishizaka_-_03_-_Variatio_2_a_1_Clav.ogg/Kimiko_Ishizaka_-_03_-_Variatio_2_a_1_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 3 a 1 Clav Canone allUnisuono",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 4,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 117000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/21/Kimiko_Ishizaka_-_04_-_Variatio_3_a_1_Clav_Canone_allUnisuono.ogg/Kimiko_Ishizaka_-_04_-_Variatio_3_a_1_Clav_Canone_allUnisuono.ogg.mp3",
    },
    Seed {
        title: "Variatio 4 a 1 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 5,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 69000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f0/Kimiko_Ishizaka_-_05_-_Variatio_4_a_1_Clav.ogg/Kimiko_Ishizaka_-_05_-_Variatio_4_a_1_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 5 a 1 ovvero 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 6,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 94000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9d/Kimiko_Ishizaka_-_06_-_Variatio_5_a_1_ovvero_2_Clav.ogg/Kimiko_Ishizaka_-_06_-_Variatio_5_a_1_ovvero_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 6 a 1 Clav Canone alla Seconda",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 7,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 98000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f9/Kimiko_Ishizaka_-_07_-_Variatio_6_a_1_Clav_Canone_alla_Seconda.ogg/Kimiko_Ishizaka_-_07_-_Variatio_6_a_1_Clav_Canone_alla_Seconda.ogg.mp3",
    },
    Seed {
        title: "Variatio 7 a 1 ovvero 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 8,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 132000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1b/Kimiko_Ishizaka_-_08_-_Variatio_7_a_1_ovvero_2_Clav.ogg/Kimiko_Ishizaka_-_08_-_Variatio_7_a_1_ovvero_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 8 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 9,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 117000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/bc/Kimiko_Ishizaka_-_09_-_Variatio_8_a_2_Clav.ogg/Kimiko_Ishizaka_-_09_-_Variatio_8_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 9 a 1 Clav Canone alla Terza",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 10,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 126000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/21/Kimiko_Ishizaka_-_10_-_Variatio_9_a_1_Clav_Canone_alla_Terza.ogg/Kimiko_Ishizaka_-_10_-_Variatio_9_a_1_Clav_Canone_alla_Terza.ogg.mp3",
    },
    Seed {
        title: "Variatio 10 a 1 Clav Fughetta",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 11,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 106000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f6/Kimiko_Ishizaka_-_11_-_Variatio_10_a_1_Clav_Fughetta.ogg/Kimiko_Ishizaka_-_11_-_Variatio_10_a_1_Clav_Fughetta.ogg.mp3",
    },
    Seed {
        title: "Variatio 11 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 12,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 129000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2f/Kimiko_Ishizaka_-_12_-_Variatio_11_a_2_Clav.ogg/Kimiko_Ishizaka_-_12_-_Variatio_11_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 12 Canone alla Quarta",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 13,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 136000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e2/Kimiko_Ishizaka_-_13_-_Variatio_12_Canone_alla_Quarta.ogg/Kimiko_Ishizaka_-_13_-_Variatio_12_Canone_alla_Quarta.ogg.mp3",
    },
    Seed {
        title: "Variatio 13 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 14,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 254000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/49/Kimiko_Ishizaka_-_14_-_Variatio_13_a_2_Clav.ogg/Kimiko_Ishizaka_-_14_-_Variatio_13_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 14 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 15,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 137000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d9/Kimiko_Ishizaka_-_15_-_Variatio_14_a_2_Clav.ogg/Kimiko_Ishizaka_-_15_-_Variatio_14_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 15 a 1 Clav Canone alla Quinta",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 16,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 273000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2e/Kimiko_Ishizaka_-_16_-_Variatio_15_a_1_Clav_Canone_alla_Quinta.ogg/Kimiko_Ishizaka_-_16_-_Variatio_15_a_1_Clav_Canone_alla_Quinta.ogg.mp3",
    },
    Seed {
        title: "Variatio 16 a 1 Clav Ouverture",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 17,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 189000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/af/Kimiko_Ishizaka_-_17_-_Variatio_16_a_1_Clav_Ouverture.ogg/Kimiko_Ishizaka_-_17_-_Variatio_16_a_1_Clav_Ouverture.ogg.mp3",
    },
    Seed {
        title: "Variatio 17 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 18,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 104000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4b/Kimiko_Ishizaka_-_18_-_Variatio_17_a_2_Clav.ogg/Kimiko_Ishizaka_-_18_-_Variatio_17_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 18 a 1 Clav Canone alla Sexta",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 19,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 109000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/75/Kimiko_Ishizaka_-_19_-_Variatio_18_a_1_Clav_Canone_alla_Sexta.ogg/Kimiko_Ishizaka_-_19_-_Variatio_18_a_1_Clav_Canone_alla_Sexta.ogg.mp3",
    },
    Seed {
        title: "Variatio 19 a 1 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 20,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 85000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1e/Kimiko_Ishizaka_-_20_-_Variatio_19_a_1_Clav.ogg/Kimiko_Ishizaka_-_20_-_Variatio_19_a_1_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 20 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 21,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 125000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f9/Kimiko_Ishizaka_-_21_-_Variatio_20_a_2_Clav.ogg/Kimiko_Ishizaka_-_21_-_Variatio_20_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 21 Canone alla Settima",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 22,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 235000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/02/Kimiko_Ishizaka_-_22_-_Variatio_21_Canone_alla_Settima.ogg/Kimiko_Ishizaka_-_22_-_Variatio_21_Canone_alla_Settima.ogg.mp3",
    },
    Seed {
        title: "Variatio 22 a 1 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 23,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 93000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e8/Kimiko_Ishizaka_-_23_-_Variatio_22_a_1_Clav.ogg/Kimiko_Ishizaka_-_23_-_Variatio_22_a_1_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 23 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 24,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 140000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/ec/Kimiko_Ishizaka_-_24_-_Variatio_23_a_2_Clav.ogg/Kimiko_Ishizaka_-_24_-_Variatio_23_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 24 a 1 Clav Canone allOttava",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 25,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 165000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9f/Kimiko_Ishizaka_-_25_-_Variatio_24_a_1_Clav_Canone_allOttava.ogg/Kimiko_Ishizaka_-_25_-_Variatio_24_a_1_Clav_Canone_allOttava.ogg.mp3",
    },
    Seed {
        title: "Variatio 25 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 26,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 558000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5f/Kimiko_Ishizaka_-_26_-_Variatio_25_a_2_Clav.ogg/Kimiko_Ishizaka_-_26_-_Variatio_25_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 26 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 27,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 123000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e4/Kimiko_Ishizaka_-_27_-_Variatio_26_a_2_Clav.ogg/Kimiko_Ishizaka_-_27_-_Variatio_26_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 27 a 2 Clav Canone alla Nona",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 28,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 111000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/8f/Kimiko_Ishizaka_-_28_-_Variatio_27_a_2_Clav_Canone_alla_Nona.ogg/Kimiko_Ishizaka_-_28_-_Variatio_27_a_2_Clav_Canone_alla_Nona.ogg.mp3",
    },
    Seed {
        title: "Variatio 28 a 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 29,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 146000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a5/Kimiko_Ishizaka_-_29_-_Variatio_28_a_2_Clav.ogg/Kimiko_Ishizaka_-_29_-_Variatio_28_a_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 29 a 1 ovvero 2 Clav",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 30,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 129000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0d/Kimiko_Ishizaka_-_30_-_Variatio_29_a_1_ovvero_2_Clav.ogg/Kimiko_Ishizaka_-_30_-_Variatio_29_a_1_ovvero_2_Clav.ogg.mp3",
    },
    Seed {
        title: "Variatio 30 a 1 Clav Quodlibet",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 31,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 121000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c3/Kimiko_Ishizaka_-_31_-_Variatio_30_a_1_Clav_Quodlibet.ogg/Kimiko_Ishizaka_-_31_-_Variatio_30_a_1_Clav_Quodlibet.ogg.mp3",
    },
    Seed {
        title: "Aria da Capo Fine",
        composer: "Johann Sebastian Bach",
        album: "Goldberg Variations, BWV 988",
        part: "",
        track: 32,
        catalogue: "BWV 988",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 170000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/ee/Kimiko_Ishizaka_-_32_-_Aria_da_Capo_Fine.ogg/Kimiko_Ishizaka_-_32_-_Aria_da_Capo_Fine.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 1 in C major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 1,
        catalogue: "BWV 846",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 163000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/6b/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_01_Prelude_No._1_in_C_major%2C_BWV_846.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_01_Prelude_No._1_in_C_major%2C_BWV_846.flac.mp3",
    },
    Seed {
        title: "Fugue No. 1 in C major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 2,
        catalogue: "BWV 846",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 116000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e1/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_02_Fugue_No._1_in_C_major%2C_BWV_846.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_02_Fugue_No._1_in_C_major%2C_BWV_846.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 2 in C minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 3,
        catalogue: "BWV 847",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 107000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4d/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_03_Prelude_No._2_in_C_minor%2C_BWV_847.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_03_Prelude_No._2_in_C_minor%2C_BWV_847.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 2 in C minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 4,
        catalogue: "BWV 847",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 116000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b0/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_04_Fugue_No._2_in_C_minor%2C_BWV_847.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_04_Fugue_No._2_in_C_minor%2C_BWV_847.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 3 in C-sharp major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 5,
        catalogue: "BWV 848",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 75000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/7f/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_05_Prelude_No._3_in_C-sharp_major%2C_BWV_848.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_05_Prelude_No._3_in_C-sharp_major%2C_BWV_848.flac.mp3",
    },
    Seed {
        title: "Fugue No. 3 in C-sharp major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 6,
        catalogue: "BWV 848",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 155000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b7/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_06_Fugue_No._3_in_C-sharp_major%2C_BWV_848.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_06_Fugue_No._3_in_C-sharp_major%2C_BWV_848.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 4 in C-sharp minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 7,
        catalogue: "BWV 849",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 178000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/96/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_07_Prelude_No._4_in_C-sharp_minor%2C_BWV_849.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_07_Prelude_No._4_in_C-sharp_minor%2C_BWV_849.flac.mp3",
    },
    Seed {
        title: "Fugue No. 4 in C-sharp minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 8,
        catalogue: "BWV 849",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 161000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/21/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_08_Fugue_No._4_in_C-sharp_minor%2C_BWV_849.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_08_Fugue_No._4_in_C-sharp_minor%2C_BWV_849.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 5 in D major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 9,
        catalogue: "BWV 850",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 93000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a5/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_09_Prelude_No._5_in_D_major%2C_BWV_850.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_09_Prelude_No._5_in_D_major%2C_BWV_850.flac.mp3",
    },
    Seed {
        title: "Fugue No. 5 in D major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 10,
        catalogue: "BWV 850",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 108000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d4/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_10_Fugue_No._5_in_D_major%2C_BWV_850.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_10_Fugue_No._5_in_D_major%2C_BWV_850.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 6 in D minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 11,
        catalogue: "BWV 851",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 98000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/71/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_11_Prelude_No._6_in_D_minor%2C_BWV_851.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_11_Prelude_No._6_in_D_minor%2C_BWV_851.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 6 in D minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 12,
        catalogue: "BWV 851",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 129000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/ff/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_12_Fugue_No._6_in_D_minor%2C_BWV_851.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_12_Fugue_No._6_in_D_minor%2C_BWV_851.flac.mp3",
    },
    Seed {
        title: "Prelude No. 7 in E-flat major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 13,
        catalogue: "BWV 852",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 214000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/aa/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_13_Prelude_No._7_in_E-flat_major%2C_BWV_852.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_13_Prelude_No._7_in_E-flat_major%2C_BWV_852.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 7 in E-flat major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 14,
        catalogue: "BWV 852",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 109000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/7b/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_14_Fugue_No._7_in_E-flat_major%2C_BWV_852.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_14_Fugue_No._7_in_E-flat_major%2C_BWV_852.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 8 in E-flat minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 15,
        catalogue: "BWV 853",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 238000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/35/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_15_Prelude_No._8_in_E-flat_minor%2C_BWV_853.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_15_Prelude_No._8_in_E-flat_minor%2C_BWV_853.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 8 in D-sharp minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 16,
        catalogue: "BWV 853",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 235000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b2/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_16_Fugue_No._8_in_D-sharp_minor%2C_BWV_853.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_16_Fugue_No._8_in_D-sharp_minor%2C_BWV_853.flac.mp3",
    },
    Seed {
        title: "Prelude No. 9 in E major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 17,
        catalogue: "BWV 854",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 105000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/bc/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_17_Prelude_No._9_in_E_major%2C_BWV_854.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_17_Prelude_No._9_in_E_major%2C_BWV_854.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 9 in E major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 18,
        catalogue: "BWV 854",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 81000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2d/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_18_Fugue_No._9_in_E_major%2C_BWV_854.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_18_Fugue_No._9_in_E_major%2C_BWV_854.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 10 in E minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 19,
        catalogue: "BWV 855",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 121000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/ca/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_19_Prelude_No._10_in_E_minor%2C_BWV_855.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_19_Prelude_No._10_in_E_minor%2C_BWV_855.flac.mp3",
    },
    Seed {
        title: "Fugue No. 10 in E minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 20,
        catalogue: "BWV 855",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 90000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/8b/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_20_Fugue_No._10_in_E_minor%2C_BWV_855.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_20_Fugue_No._10_in_E_minor%2C_BWV_855.flac.mp3",
    },
    Seed {
        title: "Prelude No. 11 in F major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 21,
        catalogue: "BWV 856",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 64000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4a/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_21_Prelude_No._11_in_F_major%2C_BWV_856.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_21_Prelude_No._11_in_F_major%2C_BWV_856.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 11 in F major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 22,
        catalogue: "BWV 856",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 87000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e8/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_22_Fugue_No._11_in_F_major%2C_BWV_856.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_22_Fugue_No._11_in_F_major%2C_BWV_856.flac.mp3",
    },
    Seed {
        title: "Prelude No. 12 in F minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 23,
        catalogue: "BWV 857",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 173000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fa/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_23_Prelude_No._12_in_F_minor%2C_BWV_857.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_23_Prelude_No._12_in_F_minor%2C_BWV_857.flac.mp3",
    },
    Seed {
        title: "Fugue No. 12 in F minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 24,
        catalogue: "BWV 857",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 237000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b9/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_24_Fugue_No._12_in_F_minor%2C_BWV_857.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_24_Fugue_No._12_in_F_minor%2C_BWV_857.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 13 in F-sharp major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 25,
        catalogue: "BWV 858",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 100000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e0/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_25_Prelude_No._13_in_F-sharp_major%2C_BWV_858.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_25_Prelude_No._13_in_F-sharp_major%2C_BWV_858.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 13 in F-sharp major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 26,
        catalogue: "BWV 858",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 126000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a6/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_26_Fugue_No._13_in_F-sharp_major%2C_BWV_858.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_26_Fugue_No._13_in_F-sharp_major%2C_BWV_858.flac.mp3",
    },
    Seed {
        title: "Prelude No. 14 in F-sharp minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 27,
        catalogue: "BWV 859",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 65000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/91/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_27_Prelude_No._14_in_F-sharp_minor%2C_BWV_859.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_27_Prelude_No._14_in_F-sharp_minor%2C_BWV_859.flac.mp3",
    },
    Seed {
        title: "Fugue No. 14 in F-sharp minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 28,
        catalogue: "BWV 859",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 196000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0d/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_28_Fugue_No._14_in_F-sharp_minor%2C_BWV_859.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_28_Fugue_No._14_in_F-sharp_minor%2C_BWV_859.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 15 in G major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 29,
        catalogue: "BWV 860",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 55000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/32/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_29_Prelude_No._15_in_G_major%2C_BWV_860.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_29_Prelude_No._15_in_G_major%2C_BWV_860.flac.mp3",
    },
    Seed {
        title: "Fugue No. 15 in G major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 30,
        catalogue: "BWV 860",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 156000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1b/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_30_Fugue_No._15_in_G_major%2C_BWV_860.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_30_Fugue_No._15_in_G_major%2C_BWV_860.flac.mp3",
    },
    Seed {
        title: "Prelude No. 16 in G minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 31,
        catalogue: "BWV 861",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 134000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b6/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_31_Prelude_No._16_in_G_minor%2C_BWV_861.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_31_Prelude_No._16_in_G_minor%2C_BWV_861.flac.mp3",
    },
    Seed {
        title: "Fugue No. 16 in G minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 32,
        catalogue: "BWV 861",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 113000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/23/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_32_Fugue_No._16_in_G_minor%2C_BWV_861.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_32_Fugue_No._16_in_G_minor%2C_BWV_861.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 17 in A-flat major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 33,
        catalogue: "BWV 862",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 93000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/95/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_33_Prelude_No._17_in_A-flat_major%2C_BWV_862.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_33_Prelude_No._17_in_A-flat_major%2C_BWV_862.flac.mp3",
    },
    Seed {
        title: "Fugue No. 17 in A-flat major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 34,
        catalogue: "BWV 862",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 120000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/23/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_34_Fugue_No._17_in_A-flat_major%2C_BWV_862.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_34_Fugue_No._17_in_A-flat_major%2C_BWV_862.flac.mp3",
    },
    Seed {
        title: "Prelude No. 18 in G-sharp minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 35,
        catalogue: "BWV 863",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 122000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fd/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_35_Prelude_No._18_in_G-sharp_minor%2C_BWV_863.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_35_Prelude_No._18_in_G-sharp_minor%2C_BWV_863.flac.mp3",
    },
    Seed {
        title: "Fugue No. 18 in G-sharp minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 36,
        catalogue: "BWV 863",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 137000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c6/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_36_Fugue_No._18_in_G-sharp_minor%2C_BWV_863.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_36_Fugue_No._18_in_G-sharp_minor%2C_BWV_863.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 19 in A major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 37,
        catalogue: "BWV 864",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 91000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/88/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_37_Prelude_No._19_in_A_major%2C_BWV_864.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_37_Prelude_No._19_in_A_major%2C_BWV_864.flac.mp3",
    },
    Seed {
        title: "Fugue No. 19 in A major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 38,
        catalogue: "BWV 864",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 117000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/55/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_38_Fugue_No._19_in_A_major%2C_BWV_864.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_38_Fugue_No._19_in_A_major%2C_BWV_864.flac.mp3",
    },
    Seed {
        title: "Prelude No. 20 in A minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 39,
        catalogue: "BWV 865",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 85000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9f/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_39_Prelude_No._20_in_A_minor%2C_BWV_865.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_39_Prelude_No._20_in_A_minor%2C_BWV_865.ogg.mp3",
    },
    Seed {
        title: "Fugue No. 20 in A minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 40,
        catalogue: "BWV 865",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 245000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c0/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_40_Fugue_No._20_in_A_minor%2C_BWV_865.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_40_Fugue_No._20_in_A_minor%2C_BWV_865.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 21 in B-flat major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 41,
        catalogue: "BWV 866",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 79000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1f/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_41_Prelude_No._21_in_B-flat_major%2C_BWV_866.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_41_Prelude_No._21_in_B-flat_major%2C_BWV_866.flac.mp3",
    },
    Seed {
        title: "Fugue No. 21 in B-flat major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 42,
        catalogue: "BWV 866",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 116000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/57/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_42_Fugue_No._21_in_B-flat_major%2C_BWV_866.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_42_Fugue_No._21_in_B-flat_major%2C_BWV_866.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 22 in B-flat minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 43,
        catalogue: "BWV 867",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 148000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/ba/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_43_Prelude_No._22_in_B-flat_minor%2C_BWV_867.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_43_Prelude_No._22_in_B-flat_minor%2C_BWV_867.flac.mp3",
    },
    Seed {
        title: "Fugue No. 22 in B-flat minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 44,
        catalogue: "BWV 867",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 198000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5d/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_44_Fugue_No._22_in_B-flat_minor%2C_BWV_867.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_44_Fugue_No._22_in_B-flat_minor%2C_BWV_867.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 23 in B major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 45,
        catalogue: "BWV 868",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 60000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fb/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_45_Prelude_No._23_in_B_major%2C_BWV_868.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_45_Prelude_No._23_in_B_major%2C_BWV_868.flac.mp3",
    },
    Seed {
        title: "Fugue No. 23 in B major",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 46,
        catalogue: "BWV 868",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 109000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/88/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_46_Fugue_No._23_in_B_major%2C_BWV_868.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_46_Fugue_No._23_in_B_major%2C_BWV_868.ogg.mp3",
    },
    Seed {
        title: "Prelude No. 24 in B minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 47,
        catalogue: "BWV 869",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 148000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/7b/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_47_Prelude_No._24_in_B_minor%2C_BWV_869.flac/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_47_Prelude_No._24_in_B_minor%2C_BWV_869.flac.mp3",
    },
    Seed {
        title: "Fugue No. 24 in B minor",
        composer: "Johann Sebastian Bach",
        album: "The Well-Tempered Clavier",
        part: "Book I",
        track: 48,
        catalogue: "BWV 869",
        performer: "Kimiko Ishizaka",
        licence: "",
        bpm: 0,
        ms: 482000,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5d/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_48_Fugue_No._24_in_B_minor%2C_BWV_869.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_48_Fugue_No._24_in_B_minor%2C_BWV_869.ogg.mp3",
    },
];
// BACH-END

/// The six Brandenburg Concertos, which are complete only if a credit is given.
///
/// Every no-rights-reserved Brandenburg on Commons is a fragment — a coda, the
/// closing bars, a five-second MIDI cadence — so the rule the rest of the seed
/// follows would have left the most famous thing Bach wrote out of a Bach
/// library. What is complete is licensed CC BY or CC BY-SA, which is not a
/// refusal but a condition: name whoever made it, and say under what.
///
/// So [`Seed::licence`] exists and is drawn beside the performer. The credit is
/// not a comment in this file where nobody would see it — the album page shows
/// the performer, and for these rows it shows what the licence was as well.
///
/// The concertos are one album in six parts, which is what the album page's
/// section headings are for. Nos. 1 and 4 are two recordings between them, and
/// that is visible rather than hidden: the performer column changes where the
/// recording does.
pub const BRANDENBURG: &[Seed] = &[
    Seed {
        title: "I. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 1 in F major, BWV 1046",
        track: 1,
        catalogue: "BWV 1046",
        performer: "Busch Chamber Players",
        licence: "CC BY 3.0",
        bpm: 138,
        ms: 276452,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f4/Bach_-_Brandenburg_Concerto_No._1_-_1._Allegro.ogg/Bach_-_Brandenburg_Concerto_No._1_-_1._Allegro.ogg.mp3",
    },
    Seed {
        title: "II. Adagio",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 1 in F major, BWV 1046",
        track: 2,
        catalogue: "BWV 1046",
        performer: "Busch Chamber Players",
        licence: "CC BY-SA 3.0",
        bpm: 71,
        ms: 281967,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1f/Bach_-_Brandenburg_Concerto.No.1_in_F_Major-_II._Adagio.ogg/Bach_-_Brandenburg_Concerto.No.1_in_F_Major-_II._Adagio.ogg.mp3",
    },
    Seed {
        title: "III. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 1 in F major, BWV 1046",
        track: 3,
        catalogue: "BWV 1046",
        performer: "Busch Chamber Players",
        licence: "CC BY-SA 3.0",
        bpm: 138,
        ms: 272877,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/18/Bach_-_Brandenburg_Concerto.No._1_in_F_Major-_III._Allegro.ogg/Bach_-_Brandenburg_Concerto.No._1_in_F_Major-_III._Allegro.ogg.mp3",
    },
    Seed {
        title: "IV. Menuetto - Trio - Polacca",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 1 in F major, BWV 1046",
        track: 4,
        catalogue: "BWV 1046",
        performer: "Busch Chamber Players",
        licence: "CC BY-SA 3.0",
        bpm: 120,
        ms: 480184,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/95/Bach_-_Brandenburg_Concerto.No.1_in_F_Major-_IV._Menuetto%3B_Trio_1%3B_Menuetto%3B_Polacca%3B_Menuetto_and_Trio.ogg/Bach_-_Brandenburg_Concerto.No.1_in_F_Major-_IV._Menuetto%3B_Trio_1%3B_Menuetto%3B_Polacca%3B_Menuetto_and_Trio.ogg.mp3",
    },
    Seed {
        title: "I. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 2 in F major, BWV 1047",
        track: 1,
        catalogue: "BWV 1047",
        performer: "Vince DiMartino and the Lexington Bach Choir Orchestra",
        licence: "CC BY 3.0",
        bpm: 138,
        ms: 317100,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/46/IMSLP83563_-_Brandenburg_Concerto_No.2_in_F_major%2C_BWV_1047_%28Bach%2C_Johann_Sebastian%29_-_1._%28Allegro%29.ogg/IMSLP83563_-_Brandenburg_Concerto_No.2_in_F_major%2C_BWV_1047_%28Bach%2C_Johann_Sebastian%29_-_1._%28Allegro%29.ogg.mp3",
    },
    Seed {
        title: "II. Andante",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 2 in F major, BWV 1047",
        track: 2,
        catalogue: "BWV 1047",
        performer: "Vince DiMartino and the Lexington Bach Choir Orchestra",
        licence: "CC BY 3.0",
        bpm: 92,
        ms: 197695,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/44/IMSLP83567_-_Brandenburg_Concerto_No.2_in_F_major%2C_BWV_1047_%28Bach%2C_Johann_Sebastian%29_-_2._Andante.ogg/IMSLP83567_-_Brandenburg_Concerto_No.2_in_F_major%2C_BWV_1047_%28Bach%2C_Johann_Sebastian%29_-_2._Andante.ogg.mp3",
    },
    Seed {
        title: "III. Allegro assai",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 2 in F major, BWV 1047",
        track: 3,
        catalogue: "BWV 1047",
        performer: "Vince DiMartino and the Lexington Bach Choir Orchestra",
        licence: "CC BY 3.0",
        bpm: 144,
        ms: 224052,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/3a/IMSLP83569_-_Brandenburg_Concerto_No.2_in_F_major%2C_BWV_1047_%28Bach%2C_Johann_Sebastian%29_-_3._Allegro_assai.ogg/IMSLP83569_-_Brandenburg_Concerto_No.2_in_F_major%2C_BWV_1047_%28Bach%2C_Johann_Sebastian%29_-_3._Allegro_assai.ogg.mp3",
    },
    Seed {
        title: "I. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 3 in G major, BWV 1048",
        track: 1,
        catalogue: "BWV 1048",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 138,
        ms: 319164,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b0/Bach_-_Brandenburg_Concerto_No._3_-_1._Allegro.ogg/Bach_-_Brandenburg_Concerto_No._3_-_1._Allegro.ogg.mp3",
    },
    Seed {
        title: "II. Adagio",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 3 in G major, BWV 1048",
        track: 2,
        catalogue: "BWV 1048",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 71,
        ms: 23613,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/78/Bach_-_Brandenburg_Concerto_No._3_-_2._Adagio.ogg/Bach_-_Brandenburg_Concerto_No._3_-_2._Adagio.ogg.mp3",
    },
    Seed {
        title: "III. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 3 in G major, BWV 1048",
        track: 3,
        catalogue: "BWV 1048",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 138,
        ms: 273613,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/ca/Bach_-_Brandenburg_Concerto_No._3_-_3._Allegro.ogg/Bach_-_Brandenburg_Concerto_No._3_-_3._Allegro.ogg.mp3",
    },
    Seed {
        title: "I. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 4 in G major, BWV 1049",
        track: 1,
        catalogue: "BWV 1049",
        performer: "Kevin MacLeod",
        licence: "CC BY 3.0",
        bpm: 138,
        ms: 437603,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/18/Kevin_MacLeod_-_J_S_Bach_Brandenburg_Concerto_No4-1_BWV1049.ogg/Kevin_MacLeod_-_J_S_Bach_Brandenburg_Concerto_No4-1_BWV1049.ogg.mp3",
    },
    Seed {
        title: "II. Andante",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 4 in G major, BWV 1049",
        track: 2,
        catalogue: "BWV 1049",
        performer: "Busch Chamber Players",
        licence: "CC BY-SA 3.0",
        bpm: 92,
        ms: 275959,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b9/Bach_-_Brandenburg_ConcertoNo._4_in_G_Major-_II._Andante.ogg/Bach_-_Brandenburg_ConcertoNo._4_in_G_Major-_II._Andante.ogg.mp3",
    },
    Seed {
        title: "III. Presto",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 4 in G major, BWV 1049",
        track: 3,
        catalogue: "BWV 1049",
        performer: "Busch Chamber Players",
        licence: "CC BY-SA 3.0",
        bpm: 184,
        ms: 256942,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/26/Bach_-_Brandenburg_Concerto.No.4_in_G_Major-_III._Presto.ogg/Bach_-_Brandenburg_Concerto.No.4_in_G_Major-_III._Presto.ogg.mp3",
    },
    Seed {
        title: "I. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 5 in D major, BWV 1050",
        track: 1,
        catalogue: "BWV 1050",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 138,
        ms: 598533,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/68/Bach_-_Brandenburg_Concerto_5_-_1._Allegro.ogg/Bach_-_Brandenburg_Concerto_5_-_1._Allegro.ogg.mp3",
    },
    Seed {
        title: "II. Affettuoso",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 5 in D major, BWV 1050",
        track: 2,
        catalogue: "BWV 1050",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 0,
        ms: 355960,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/49/Bach_-_Brandenburg_Concerto_5_-_2._Affettuoso.ogg/Bach_-_Brandenburg_Concerto_5_-_2._Affettuoso.ogg.mp3",
    },
    Seed {
        title: "III. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 5 in D major, BWV 1050",
        track: 3,
        catalogue: "BWV 1050",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 138,
        ms: 296995,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/12/Bach_-_Brandenburg_Concerto_5_-_3._Allegro.ogg/Bach_-_Brandenburg_Concerto_5_-_3._Allegro.ogg.mp3",
    },
    Seed {
        title: "I. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 6 in B-flat major, BWV 1051",
        track: 1,
        catalogue: "BWV 1051",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 138,
        ms: 340707,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f3/Bach_-_Brandenburg_Concerto_6_-_1._Allegro.ogg/Bach_-_Brandenburg_Concerto_6_-_1._Allegro.ogg.mp3",
    },
    Seed {
        title: "II. Adagio ma non tanto",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 6 in B-flat major, BWV 1051",
        track: 2,
        catalogue: "BWV 1051",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 71,
        ms: 312231,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/37/Bach_-_Brandenburg_Concerto_6_-_2._Adagio.ogg/Bach_-_Brandenburg_Concerto_6_-_2._Adagio.ogg.mp3",
    },
    Seed {
        title: "III. Allegro",
        composer: "Johann Sebastian Bach",
        album: "Brandenburg Concertos",
        part: "Concerto No. 6 in B-flat major, BWV 1051",
        track: 3,
        catalogue: "BWV 1051",
        performer: "Advent Chamber Orchestra",
        licence: "CC BY-SA 2.0",
        bpm: 138,
        ms: 335912,
        file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/61/Bach_-_Brandenburg_Concerto_6_-_3._Allegro.ogg/Bach_-_Brandenburg_Concerto_6_-_3._Allegro.ogg.mp3",
    },
];

/// Put something in an empty demo library, so the page has a list on it.
///
/// Through `mutate`, not through SQL: the demo runs the same `apply` as
/// every other peer, and seeding it any other way would be showing
/// something the engine did not do.
pub fn seed(peer: &mut Peer) {
    if !peer.items.is_empty() {
        return;
    }
    // Public-domain recordings on Wikimedia Commons, by way of the mp3
    // Commons transcodes every audio file gets: a browser plays mp3
    // everywhere, and Vorbis in an `.ogg` does not play in Safari at all.
    //
    // The URL goes in `file`, which is what that column has always been
    // for — "the bytes travel over HTTP and only the name of them is
    // synced". Nothing about the log changes to carry a recording.
    //
    // Every one of these was checked: public domain by Commons' own
    // licence field, and a transcode that answers with `audio/mpeg` and a
    // range request. A dead link here is a silent demo, so they are not
    // taken on trust.
    const LIBRARY: &[Seed] = &[
        Seed {
            title: "Toccata and Fugue in D minor, BWV 565",
            composer: "Johann Sebastian Bach",
            album: "Organ Works",
            part: "",
            track: 0,
            catalogue: "BWV 565",
            performer: "",
            licence: "",
            bpm: 0,
            ms: 514000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/be/Toccata_et_Fugue_BWV565.ogg/Toccata_et_Fugue_BWV565.ogg.mp3",
        },
        Seed {
            title: "Für Elise",
            composer: "Ludwig van Beethoven",
            album: "Bagatelles",
            part: "",
            track: 0,
            catalogue: "WoO 59",
            performer: "",
            licence: "",
            bpm: 0,
            ms: 177000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/7b/FurElise.ogg/FurElise.ogg.mp3",
        },
        Seed {
            title: "Ballade No. 1 in G minor, Op. 23",
            composer: "Frédéric Chopin",
            album: "Ballades",
            part: "",
            track: 1,
            catalogue: "Op. 23",
            performer: "",
            licence: "",
            bpm: 0,
            ms: 679000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/33/Frederic_Chopin_-_ballade_no._1_in_g_minor%2C_op._23.ogg/Frederic_Chopin_-_ballade_no._1_in_g_minor%2C_op._23.ogg.mp3",
        },
        Seed {
            title: "Ballade No. 2 in F major, Op. 38",
            composer: "Frédéric Chopin",
            album: "Ballades",
            part: "",
            track: 2,
            catalogue: "Op. 38",
            performer: "",
            licence: "",
            bpm: 0,
            ms: 420000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/cf/Frederic_Chopin_-_ballade_no._2_in_f_major%2C_op._38.ogg/Frederic_Chopin_-_ballade_no._2_in_f_major%2C_op._38.ogg.mp3",
        },
        Seed {
            title: "Alla Hornpipe",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 2 in D major",
            track: 12,
            catalogue: "HWV 349",
            performer: "United States Marine Band",
            licence: "",
            bpm: 120,
            ms: 229000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5c/Handel%27s_Water_Music_-_12._Alla_hornpipe_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_12._Alla_hornpipe_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Minuet",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 2 in D major",
            track: 13,
            catalogue: "HWV 349",
            performer: "United States Marine Band",
            licence: "",
            bpm: 120,
            ms: 195000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c9/Handel%27s_Water_Music_-_13._Minuet_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_13._Minuet_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Lentement",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 2 in D major",
            track: 14,
            catalogue: "HWV 349",
            performer: "United States Marine Band",
            licence: "",
            bpm: 60,
            ms: 136000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/75/Handel%27s_Water_Music_-_14._Lentement_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_14._Lentement_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Bourrée",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 2 in D major",
            track: 15,
            catalogue: "HWV 349",
            performer: "United States Marine Band",
            licence: "",
            bpm: 132,
            ms: 76000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2d/Handel%27s_Water_Music_-_15._Bourree_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_15._Bourree_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Sarabande",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 3 in G major",
            track: 16,
            catalogue: "HWV 350",
            performer: "United States Marine Band",
            licence: "",
            bpm: 60,
            ms: 168000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e8/Handel%27s_Water_Music_-_16._Sarabande_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_16._Sarabande_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Rigaudon",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 3 in G major",
            track: 17,
            catalogue: "HWV 350",
            performer: "United States Marine Band",
            licence: "",
            bpm: 132,
            ms: 156000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c7/Handel%27s_Water_Music_-_17._%26_18._Rigaudon_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_17._%26_18._Rigaudon_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Menuet",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 3 in G major",
            track: 19,
            catalogue: "HWV 350",
            performer: "United States Marine Band",
            licence: "",
            bpm: 120,
            ms: 227000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/ac/Handel%27s_Water_Music_-_19._%26_20._Menuet_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_19._%26_20._Menuet_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Gigue",
            composer: "George Frideric Handel",
            album: "Water Music",
            part: "Suite No. 3 in G major",
            track: 21,
            catalogue: "HWV 350",
            performer: "United States Marine Band",
            licence: "",
            bpm: 120,
            ms: 85000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fe/Handel%27s_Water_Music_-_21._%26_22._Gigue_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_21._%26_22._Gigue_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3",
        },
        Seed {
            title: "Impromptu in G-flat major, D. 899",
            composer: "Franz Schubert",
            album: "Impromptus",
            part: "",
            track: 3,
            catalogue: "D. 899",
            performer: "",
            licence: "",
            bpm: 0,
            ms: 301000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0b/Schubert_Gb_Impromptu_Andriy_Bondarenko_%28Live%29.ogg/Schubert_Gb_Impromptu_Andriy_Bondarenko_%28Live%29.ogg.mp3",
        },
        Seed {
            title: "Hungarian Dance No. 5",
            composer: "Johannes Brahms",
            album: "Hungarian Dances",
            part: "",
            track: 5,
            catalogue: "WoO 1",
            performer: "",
            licence: "",
            bpm: 0,
            ms: 175000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0a/Brahms_nikisch_hd5.ogg/Brahms_nikisch_hd5.ogg.mp3",
        },
        Seed {
            title: "Clair de lune",
            composer: "Claude Debussy",
            album: "Suite bergamasque",
            part: "",
            track: 3,
            catalogue: "L. 75",
            performer: "",
            licence: "",
            bpm: 0,
            ms: 304000,
            file: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/be/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg.mp3",
        },
    ];
    for s in LIBRARY.iter().chain(BACH).chain(BRANDENBURG) {
        let _ = peer.client.mutate(mutators::add_song(
            s.title.into(),
            s.composer.into(),
            s.album.into(),
            s.ms,
            s.file.into(),
            s.track,
            s.part.into(),
            s.catalogue.into(),
            // The credit and the terms it was given on, in the one field
            // that is already on screen beside the track. A recording that
            // reserved nothing says only who played it.
            if s.licence.is_empty() {
                s.performer.into()
            } else {
                format!("{} ({})", s.performer, s.licence)
            },
            s.bpm,
        ));
    }
    peer.refresh();
    // A few of them hearted, so the playlist is not empty either.
    let hearted: Vec<harken::Id<harken::tables::Media>> = peer
        .items
        .iter()
        .filter(|i| {
            matches!(
                i.title.as_str(),
                "Clair de lune" | "Für Elise" | "Alla Hornpipe"
            )
        })
        .map(|i| i.id)
        .collect();
    for id in hearted {
        let _ = peer
            .client
            .mutate(mutators::add_to_playlist(peer.playlist, id));
    }
    peer.refresh();

    // Two more playlists, so the sidebar shows what a playlist *is* here:
    // an ordered list somebody made, of which "Favourites" is one and not
    // a special case. Made after the hearts above so that the first
    // playlist — the one a heart means — stays Favourites.
    const SETS: &[(&str, &[&str])] = &[
        (
            "Piano",
            &[
                "Für Elise",
                "Clair de lune",
                "Ballade No. 1 in G minor, Op. 23",
                "Impromptu in G-flat major, D. 899",
                "Aria",
            ],
        ),
        (
            "Water Music",
            &["Alla Hornpipe", "Bourrée", "Sarabande", "Gigue"],
        ),
    ];
    for (name, titles) in SETS {
        let _ = peer
            .client
            .mutate(mutators::create_playlist((*name).into()));
        peer.refresh();
        let Some(list) = peer.choices.iter().find_map(|c| match &c.source {
            Source::Playlist(id, n) if n == name => Some(*id),
            _ => None,
        }) else {
            continue;
        };
        let ids: Vec<harken::Id<harken::tables::Media>> = titles
            .iter()
            .filter_map(|t| peer.items.iter().find(|i| i.title == *t))
            .map(|i| i.id)
            .collect();
        for id in ids {
            let _ = peer.client.mutate(mutators::add_to_playlist(list, id));
        }
        peer.refresh();
    }
}
