#!/usr/bin/env bash
# Generated by `nix run .#write-files` from the petros-js mobile module.
set -euo pipefail
stage="${1:?usage: eas-rust.sh pre|post}"
root="$PWD"
while [ ! -f "$root/Cargo.toml" ] && [ "$root" != "/" ]; do root="$(dirname "$root")"; done
[ -f "$root/Cargo.toml" ] || { echo "eas-rust: no cargo workspace above $PWD" >&2; exit 1; }
app="$PWD"

case "$stage" in
  pre)
    if command -v cargo >/dev/null && command -v cargo-ndk >/dev/null; then
      echo "--- rust already present: $(rustc --version)"; exit 0
    fi
    echo "--- installing Rust $RUST_VERSION for $(uname -m)"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
      | sh -s -- -y --default-toolchain none --profile minimal --no-modify-path
    . "$HOME/.cargo/env"
    # shellcheck disable=SC2086
    rustup toolchain install "$RUST_VERSION" --profile minimal \
      $(for t in $RUST_TARGETS; do printf ' --target %s' "$t"; done)
    rustup default "$RUST_VERSION"
    cargo install cargo-ndk --locked --version '^3'
    ;;
  post)
    . "$HOME/.cargo/env"
    if [ -z "${ANDROID_NDK_HOME:-}" ] && [ -d "${ANDROID_SDK_ROOT:-}/ndk" ]; then
      ANDROID_NDK_HOME="$(ls -d "$ANDROID_SDK_ROOT"/ndk/* | sort -V | tail -1)"; export ANDROID_NDK_HOME
    fi
    echo "--- ndk: ${ANDROID_NDK_HOME:-<none>}"
    cd "$root"
    echo "--- the mutator module"
    cargo build -p harken --no-default-features \
      --target wasm32-unknown-unknown --profile mutators
    # The generator at the engine's own revision, so it agrees with the
    # module about the schema section; kept in target/ for a second
    # build in the same container.
    [ -x target/codegen/bin/petros-codegen ] || cargo install --quiet \
      --git https://github.com/k2on/petros --rev "$PETROS_REV" --root target/codegen petros-codegen
    target/codegen/bin/petros-codegen \
      target/wasm32-unknown-unknown/mutators/harken.wasm \
      mobile/src/mutators.gen.ts
    echo "--- the engine, cross-compiled"
    cd "$app/modules/harken-native"
    "$app/node_modules/.bin/ubrn" build android --config ubrn.config.yaml --and-generate --release
    ;;
  *) echo "eas-rust: unknown stage \"$stage\"" >&2; exit 1 ;;
esac
