android:
  apiLevel: 24
  cargoExtras:
  - --features
  - foreign
  directory: android
  targets:
  - arm64-v8a
  - x86_64
bindings:
  cpp: cpp/generated
  ts: src/generated
ios:
  cargoExtras:
  - --features
  - foreign
  directory: ios
  targets:
  - aarch64-apple-ios
  - aarch64-apple-ios-sim
rust:
  directory: ../../..
  manifestPath: domain/Cargo.toml
